export const listOfAllStn=[
    {label: 'Churchgate' , value: 'Churchgate'},
    {label: 'Marine Lines' , value: 'Marine Lines'},
    {label:'Charni Road' ,  value: 'Charni Road'},
    {label:'Grant Road' ,  value: 'Grant Road'},
    {label:'Mumbai Central' ,  value: 'Mumbai Central'},
    {label:'Mahalaxmi' ,  value: 'Mahalaxmi'},
    {label:'Lower Parel' ,  value: 'Lower Parel'},
    {label:'Prabhadevi' ,  value: 'Prabhadevi'},
    {label:'Dadar (WR)' ,  value: 'Dadar (WR)'},
    {label:'Matunga (WR)' ,  value: 'Matunga (WR)'},
    {label:'Mahim' , value: 'Mahim'},
    {label:'Bandra' ,  value: 'Bandra'},
    {label:'Khar Road' ,  value: 'Khar Road'},
    {label:'Santacruz' ,  value: 'Santacruz'},
    {label: 'Vile Parle' ,  value: 'Vile Parle'},
    {label:'Andheri' ,  value: 'Andheri'},
    {label:'Jogeshwari' ,  value: 'Jogeshwari'},
    {label:'Ram Mandir' ,  value: 'Ram Mandir'},
    {label:'Goregoan' ,  value: 'Goregoan'},
    {label:'Malad' ,  value: 'Malad'},
    {label:'Kandivali' ,  value: 'Kandivali'},
    {label:'Borivali' , value: 'Borivali'},
    {label:'Dahisar' ,  value: 'Dahisar'},
    {label:'Mira Road' ,  value: 'Mira Road'},
    {label:'Bhayandar' ,  value: 'Bhayandar'},
    {label:'Naigaon' ,  value: 'Naigaon'},
    {label:'Vasai Road' ,  value: 'Vasai Road'},
    {label:'Nallasopara' ,  value: 'Nallasopara'},
    {label:'Virar' ,  value: 'Virar'},
    {label:'Vaitarna' ,  value: 'Vaitarna'},
    {label:'Saphale' ,  value: 'Saphale'},
    {label:'Kelve Road' ,  value: 'Kelve Road'},
    {label:'Palghar' , value:  'Palghar'},
    {label:'Umroli' ,  value: 'Umroli'},
    {label:'Boisar' ,  value: 'Boisar'},
    {label:'Vangaon' ,  value: 'Vangaon'},
    {label:'Dahanu Road' ,  value: 'Dahanu Road'},
    {label:'CSMT' , value:  'CSMT'},
    {label:'Masjid Bunder' ,  value: 'Masjid Bunder'},
    {label:'Sandhurst Road' , value:  'Sandhurst Road'},
    {label:'Byculla' , value:  'Byculla'},
    {label:'Chinchpokli' , value:  'Chinchpokli'},
    {label:'Currey Road' , value:  'Currey Road'},
    {label:'Parel' ,  value: 'Parel'},
    {label:'Dadar (CR)' ,  value: 'Dadar (CR)'},
    {label:'Matunga (CR)' ,  value: 'Matunga (CR)'},
    {label:'Sion' ,  value: 'Sion'},
    {label:'Kurla' ,  value: 'Kurla'},
    {label:'Vidya Vihar' , value:  'Vidya Vihar'},
    {label:'Ghatkopar' ,  value: 'Ghatkopar'},
    {label:'Viklori',  value: 'Viklori'},
    {label:'Kanjur Marg' ,  value: 'Kanjur Marg'},
    {label:'Bhandup' ,  value: 'Bhandup'},
    {label:'Nahur' ,  value: 'Nahur'},
    {label:'Mulund' ,  value: 'Mulund'},
    {label:'Thane' ,  value: 'Thane'},
    {label:'Kalwa' ,  value: 'Kalwa'},
    {label:'Mumbra' , value:  'Mumbra'},
    {label:'Diva' ,  value: 'Diva'},
    {label:'Kopar' ,  value: 'Kopar'},
    {label:'Dombivali' ,  value: 'Dombivali'},
    {label:'Thakurli' ,  value: 'Thakurli'},
    {label:'Kalyan' ,  value: 'Kalyan'}
];

export const listOfWRStn=[
    {label: 'Churchgate' , value: 'Churchgate'},
    {label: 'Marine Lines' , value: 'Marine Lines'},
    {label:'Charni Road' ,  value: 'Charni Road'},
    {label:'Grant Road' ,  value: 'Grant Road'},
    {label:'Mumbai Central' ,  value: 'Mumbai Central'},
    {label:'Mahalaxmi' ,  value: 'Mahalaxmi'},
    {label:'Lower Parel' ,  value: 'Lower Parel'},
    {label:'Prabhadevi' ,  value: 'Prabhadevi'},
    {label:'Dadar (WR)' ,  value: 'Dadar (WR)'},
    {label:'Matunga (WR)' ,  value: 'Matunga (WR)'},
    {label:'Mahim' , value: 'Mahim'},
    {label:'Bandra' ,  value: 'Bandra'},
    {label:'Khar Road' ,  value: 'Khar Road'},
    {label:'Santacruz' ,  value: 'Santacruz'},
    {label: 'Vile Parle' ,  value: 'Vile Parle'},
    {label:'Andheri' ,  value: 'Andheri'},
    {label:'Jogeshwari' ,  value: 'Jogeshwari'},
    {label:'Ram Mandir' ,  value: 'Ram Mandir'},
    {label:'Goregoan' ,  value: 'Goregoan'},
    {label:'Malad' ,  value: 'Malad'},
    {label:'Kandivali' ,  value: 'Kandivali'},
    {label:'Borivali' , value: 'Borivali'},
    {label:'Dahisar' ,  value: 'Dahisar'},
    {label:'Mira Road' ,  value: 'Mira Road'},
    {label:'Bhayandar' ,  value: 'Bhayandar'},
    {label:'Naigaon' ,  value: 'Naigaon'},
    {label:'Vasai Road' ,  value: 'Vasai Road'},
    {label:'Nallasopara' ,  value: 'Nallasopara'},
    {label:'Virar' ,  value: 'Virar'},
    {label:'Vaitarna' ,  value: 'Vaitarna'},
    {label:'Saphale' ,  value: 'Saphale'},
    {label:'Kelve Road' ,  value: 'Kelve Road'},
    {label:'Palghar' , value:  'Palghar'},
    {label:'Umroli' ,  value: 'Umroli'},
    {label:'Boisar' ,  value: 'Boisar'},
    {label:'Vangaon' ,  value: 'Vangaon'},
    {label:'Dahanu Road' ,  value: 'Dahanu Road'}
];

export const listOfCRStn = [
    {label:'CSMT' , value:  'CSMT'},
    {label:'Masjid Bunder' ,  value: 'Masjid Bunder'},
    {label:'Sandhurst Road' , value:  'Sandhurst Road'},
    {label:'Byculla' , value:  'Byculla'},
    {label:'Chinchpokli' , value:  'Chinchpokli'},
    {label:'Currey Road' , value:  'Currey Road'},
    {label:'Parel' ,  value: 'Parel'},
    {label:'Dadar (CR)' ,  value: 'Dadar (CR)'},
    {label:'Matunga (CR)' ,  value: 'Matunga (CR)'},
    {label:'Sion' ,  value: 'Sion'},
    {label:'Kurla' ,  value: 'Kurla'},
    {label:'Vidya Vihar' , value:  'Vidya Vihar'},
    {label:'Ghatkopar' ,  value: 'Ghatkopar'},
    {label:'Viklori',  value: 'Viklori'},
    {label:'Kanjur Marg' ,  value: 'Kanjur Marg'},
    {label:'Bhandup' ,  value: 'Bhandup'},
    {label:'Nahur' ,  value: 'Nahur'},
    {label:'Mulund' ,  value: 'Mulund'},
    {label:'Thane' ,  value: 'Thane'},
    {label:'Kalwa' ,  value: 'Kalwa'},
    {label:'Mumbra' , value:  'Mumbra'},
    {label:'Diva' ,  value: 'Diva'},
    {label:'Kopar' ,  value: 'Kopar'},
    {label:'Dombivali' ,  value: 'Dombivali'},
    {label:'Thakurli' ,  value: 'Thakurli'},
    {label:'Kalyan' ,  value: 'Kalyan'}
]

export const stnDistance = {
        "Churchgate" : "0",
        "Marine Lines" : "1",
        "Charni Road" : "2",
        "Grant Road" : "3",
        "Mumbai Central" : "4",
        "Mahalaxmi" : "5",
        "Lower Parel" : "7",
        "Prabhadevi" : "8",
        "Dadar (WR)" : "9",
        "Matunga (WR)" : "11",
        "Mahim" :"12",
        "Bandra" : "14",
        "Khar Road" : "16",
        "Santacruz" : "17",
        "Vile Parle" : "19",
        "Andheri" : "21",
        "Jogeshwari" : "23",
        "Ram Mandir" : "25",
        "Goregoan" : "27",
        "Malad" : "28",
        "Kandivali" : "31",
        "Borivali" : "34",
        "Dahisar" : "36",
        "Mira Road" : "39",
        "Bhayandar" : "42",
        "Naigaon" : "48",
        "Vasai Road" : "52",
        "Nallasopara" : "56",
        "Virar" : "60",
        "Vaitarna" : "68",
        "Saphale" : "74",
        "Kelve Road" : "80",
        "Palghar" : "88",
        "Umroli" : "94",
        "Boisar" : "100",
        "Vangaon" : "109",
        "Dahanu Road" : "121",
        "CSMT" : "0",
        "Masjid Bunder" : "1",
        "Sandhurst Road" : "2",
        "Byculla" : "4",
        "Chinchpokli" : "5",
        "Currey Road" : "6",
        "Parel" : "8",
        "Dadar (CR)" : "9",
        "Matunga (CR)" : "10",
        "Sion" : "11",
        "Kurla" : "12",
        "Vidya Vihar" : "14",
        "Ghatkopar" : "16",
        "Viklori": "20",
        "Kanjur Marg" : "22",
        "Bhandup" : "24",
        "Nahur" : "25",
        "Mulund" : "27",
        "Thane" : "30",
        "Kalwa" : "32",
        "Mumbra" : "35",
        "Diva" : "38",
        "Kopar" : "41",
        "Dombivali" : "45",
        "Thakurli" : "46",
        "Kalyan" : "50",
    
}